// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8IIjqsEDyGqdqgVLcM0wJ1RvnlSC4j_0',
    appId: '1:868461629414:web:b32e15fe200426ac485027',
    messagingSenderId: '868461629414',
    projectId: 'breathe-fad34',
    authDomain: 'breathe-fad34.firebaseapp.com',
    storageBucket: 'breathe-fad34.appspot.com',
    measurementId: 'G-Y07J4DD2NK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgwtKNEkjTM5GskJWyoFLTzfYQ57Fap78',
    appId: '1:868461629414:android:27320cb071974b0c485027',
    messagingSenderId: '868461629414',
    projectId: 'breathe-fad34',
    storageBucket: 'breathe-fad34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZH6f5BsngPVdajmwlIyqD_WPc6ARGq-A',
    appId: '1:868461629414:ios:e4d26ffc08fc33ce485027',
    messagingSenderId: '868461629414',
    projectId: 'breathe-fad34',
    storageBucket: 'breathe-fad34.appspot.com',
    iosClientId: '868461629414-tksni270alj18efstqa4v20jv6ohd895.apps.googleusercontent.com',
    iosBundleId: 'com.example.breathe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZH6f5BsngPVdajmwlIyqD_WPc6ARGq-A',
    appId: '1:868461629414:ios:e4d26ffc08fc33ce485027',
    messagingSenderId: '868461629414',
    projectId: 'breathe-fad34',
    storageBucket: 'breathe-fad34.appspot.com',
    iosClientId: '868461629414-tksni270alj18efstqa4v20jv6ohd895.apps.googleusercontent.com',
    iosBundleId: 'com.example.breathe',
  );
}
